### ISSUE TITLE
MVP

### ISSUE THREAD

**Issue by ngot** [ako-deno/ako#4]
# MVP of Ako

## Goal 

A minimum working prototype.

## Plan

- [ ] [Koa Packages Migration](https://github.com/orgs/ako-deno/projects/1)
    - [x] vary: https://github.com/ako-deno/vary
    - [x] escape-html: https://github.com/ako-deno/escape_html
    - [x] encodeurl: https://github.com/ako-deno/encodeurl
    - [x] http-errors: https://github.com/ako-deno/http_errors
    - [x] http-assert: no need to migrate, just write in TS based on https://github.com/jshttp/http-assert/blob/master/index.js
    - [x] content-type: https://github.com/ako-deno/content_type
    - [x] accepts: https://github.com/ako-deno/accepts
    - [x] type-is: https://github.com/ako-deno/type_is
    - [x] debug: just use https://deno.land/x/debuglog
    - [x] media-typer: https://github.com/ako-deno/media_typer
    - [x] statuses: just use `import { STATUS_TEXT } from "https://deno.land/std/http/mod.ts"`
    - [x] ms: just use https://deno.land/x/ms
    - [x] mime-types: just use https://deno.land/x/media_types
    - [x] media-typer: https://github.com/ako-deno/media_typer
    - [x] negotiator: https://github.com/ako-deno/negotiator
    - [x] isIP: https://github.com/ako-deno/isIP
    - [x] delegates: https://github.com/ako-deno/delegates
    - [x] koa-compose
        - https://github.com/DefinitelyTyped/DefinitelyTyped/commit/4e4f50a2fcbb5a635de46cc76bd6b225301b5bc3#diff-69bcb2b96efb700c5a2e74421d61ace1
        - https://github.com/DefinitelyTyped/DefinitelyTyped/commit/66001ee7644cbbc4101265cbb4be96a730114fb0#diff-69bcb2b96efb700c5a2e74421d61ace1
      - Done at https://github.com/ako-deno/ako/blob/master/src/compose.ts
    - [ ] content-disposition: https://github.com/ako-deno/cookies
    - [x] fresh: https://github.com/ako-deno/fresh-deno
    - [x] keygrip: https://github.com/ako-deno/keygrip-deno
    - [ ] cookies: https://github.com/ako-deno/cookies
    - [x] tsscmp: unnecessary, migrated to keygrip module

- [ ] Main framework prototype
    - [x] Middleware
    - [x] Error handle
    - [x] Context.body
    - [x] Context extendable with generic
    - [ ] Full Request API
    - [ ] Full Response API
    - [ ] Full Context API
    - [x] Events

**Comment by ngot** [comment]
# Todo:
- [x] _explicitNullBody
- [ ] res set message, Deno's std http does not support this yet.
- [x] this.length = Buffer.byteLength(val);
